version: '3'

networks:
  app-network:
    name: app-network
    driver: bridge
  
volumes:
  mysql:  {}

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - "../install/nginx:/var/www/html"
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    # build: ./requirements/wordpress
    container_name: wordpress
    networks:
      - app-network
    restart: always
    env_file:
      - .env
    volumes:
      - "../install/wordpress:/var/www/html"
    depends_on:
      - db
  
  db:
    image: mysql
    container_name: mariadb
    networks:
      - app-network
    restart: always
    env_file:
      - .env
    volumes:
      - "../install/mariadb:/var/lib/mysql"
      